// svelte/src/lib/components/auth/AuthDialog.svelte
<script lang="ts">
	import { getClient } from '$lib/supabase/client'
	import { invalidateAll } from '$app/navigation'

	type AuthMode = 'login' | 'register'

	interface Props {
		open: boolean
		defaultMode?: AuthMode
		onOpenChange: (open: boolean) => void
	}

	let { open = $bindable(), defaultMode = 'login', onOpenChange }: Props = $props()

	let mode = $state<AuthMode>(defaultMode)
	let email = $state('')
	let password = $state('')
	let confirmPassword = $state('')
	let error = $state<string | null>(null)
	let success = $state(false)
	let loading = $state(false)

	let dialogEl = $state<HTMLDialogElement | null>(null)

	function reset() {
		email = ''
		password = ''
		confirmPassword = ''
		error = null
		success = false
		loading = false
	}

	function switchMode(next: AuthMode) {
		reset()
		mode = next
	}

	function close() {
		reset()
		onOpenChange(false)
	}

	$effect(() => {
		if (open) {
			mode = defaultMode
			reset()
			dialogEl?.showModal()
		} else {
			dialogEl?.close()
		}
	})

	function handleBackdropClick(e: MouseEvent) {
		if (e.target === dialogEl) {
			close()
		}
	}

	function handleKeydown(e: KeyboardEvent) {
		if (e.key === 'Escape') {
			close()
		}
	}

	async function handleLogin(e: SubmitEvent) {
		e.preventDefault()
		error = null

		const trimmedEmail = email.trim()
		if (!trimmedEmail || !password) {
			error = 'Please enter both email and password.'
			return
		}

		loading = true

		const supabase = getClient()
		const { error: authError } = await supabase.auth.signInWithPassword({
			email: trimmedEmail,
			password
		})

		if (authError) {
			error = authError.message
			loading = false
			return
		}

		close()
		await invalidateAll()
	}

	async function handleRegister(e: SubmitEvent) {
		e.preventDefault()
		error = null

		const trimmedEmail = email.trim()
		if (!trimmedEmail || !password || !confirmPassword) {
			error = 'Please fill in all fields.'
			return
		}

		if (password !== confirmPassword) {
			error = 'Passwords do not match.'
			return
		}

		if (password.length < 6) {
			error = 'Password must be at least 6 characters.'
			return
		}

		loading = true

		const supabase = getClient()
		const { error: authError } = await supabase.auth.signUp({
			email: trimmedEmail,
			password
		})

		if (authError) {
			error = authError.message
			loading = false
			return
		}

		success = true
		loading = false
	}

	const isLogin = $derived(mode === 'login')
</script>

<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
<dialog
	bind:this={dialogEl}
	class="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 m-0 w-full max-w-sm rounded-lg border bg-background p-0 shadow-lg backdrop:bg-black/50"
	onclick={handleBackdropClick}
	onkeydown={handleKeydown}
	onclose={close}
>
	<div class="p-6">
		<div class="mb-4">
			<h2 class="text-lg font-semibold text-foreground">
				{isLogin ? 'Sign In' : 'Sign Up'}
			</h2>
			<p class="text-sm text-muted-foreground">
				{isLogin
					? 'Enter your credentials to access the dashboard'
					: 'Create an account to get started'}
			</p>
		</div>

		{#if success}
			<div class="space-y-4 text-center">
				<p class="text-sm text-muted-foreground">
					Check your email for a confirmation link to complete your registration.
				</p>
				<button
					type="button"
					class="w-full rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent"
					onclick={() => switchMode('login')}
				>
					Back to Sign In
				</button>
			</div>
		{:else}
			<form
				onsubmit={isLogin ? handleLogin : handleRegister}
				class="space-y-4"
				novalidate
			>
				<div class="space-y-2">
					<label for="auth-email" class="text-sm font-medium text-foreground">Email</label>
					<input
						id="auth-email"
						type="email"
						bind:value={email}
						placeholder="you@example.com"
						required
						autocomplete="email"
						class="w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:ring-2 focus:ring-ring focus:outline-none"
					/>
				</div>

				<div class="space-y-2">
					<label for="auth-password" class="text-sm font-medium text-foreground">Password</label>
					<input
						id="auth-password"
						type="password"
						bind:value={password}
						placeholder={isLogin ? 'Your password' : 'At least 6 characters'}
						required
						autocomplete={isLogin ? 'current-password' : 'new-password'}
						class="w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:ring-2 focus:ring-ring focus:outline-none"
					/>
				</div>

				{#if !isLogin}
					<div class="space-y-2">
						<label for="auth-confirm-password" class="text-sm font-medium text-foreground">
							Confirm Password
						</label>
						<input
							id="auth-confirm-password"
							type="password"
							bind:value={confirmPassword}
							placeholder="Repeat your password"
							required
							autocomplete="new-password"
							class="w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:ring-2 focus:ring-ring focus:outline-none"
						/>
					</div>
				{/if}

				{#if error}
					<p class="text-sm text-destructive" role="alert">{error}</p>
				{/if}

				<button
					type="submit"
					disabled={loading}
					class="w-full rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 disabled:opacity-50"
				>
					{#if loading}
						{isLogin ? 'Signing in...' : 'Creating account...'}
					{:else}
						{isLogin ? 'Sign In' : 'Sign Up'}
					{/if}
				</button>
			</form>

			<p class="mt-4 text-center text-sm text-muted-foreground">
				{#if isLogin}
					Don't have an account?
					<button
						type="button"
						class="font-medium text-primary underline-offset-4 hover:underline"
						onclick={() => switchMode('register')}
					>
						Sign Up
					</button>
				{:else}
					Already have an account?
					<button
						type="button"
						class="font-medium text-primary underline-offset-4 hover:underline"
						onclick={() => switchMode('login')}
					>
						Sign In
					</button>
				{/if}
			</p>
		{/if}
	</div>
</dialog>

// react/src/components/auth/auth-dialog.tsx
'use client'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { createClient } from '@/lib/supabase/client'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'

const supabase = createClient()

type AuthMode = 'login' | 'register'

interface AuthDialogProps {
  open: boolean
  onOpenChange: (open: boolean) => void
  defaultMode?: AuthMode
}

export function AuthDialog({
  open,
  onOpenChange,
  defaultMode = 'login',
}: AuthDialogProps) {
  const [mode, setMode] = useState<AuthMode>(defaultMode)

  useEffect(() => {
    if (open) {
      setMode(defaultMode)
      reset()
    }
  }, [open, defaultMode])
  const [email, setEmail] = useState('')
  const [password, setPassword] = useState('')
  const [confirmPassword, setConfirmPassword] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [success, setSuccess] = useState(false)
  const [isLoading, setIsLoading] = useState(false)
  const router = useRouter()

  const reset = () => {
    setEmail('')
    setPassword('')
    setConfirmPassword('')
    setError(null)
    setSuccess(false)
    setIsLoading(false)
  }

  const switchMode = (next: AuthMode) => {
    reset()
    setMode(next)
  }

  const handleOpenChange = (nextOpen: boolean) => {
    if (!nextOpen) reset()
    onOpenChange(nextOpen)
  }

  const handleLogin = async (e: React.FormEvent) => {
    e.preventDefault()
    setError(null)

    const trimmedEmail = email.trim()
    if (!trimmedEmail || !password) {
      setError('Please enter both email and password.')
      return
    }

    setIsLoading(true)

    const { error: authError } = await supabase.auth.signInWithPassword({
      email: trimmedEmail,
      password,
    })

    if (authError) {
      setError(authError.message)
      setIsLoading(false)
      return
    }

    handleOpenChange(false)
    router.refresh()
  }

  const handleRegister = async (e: React.FormEvent) => {
    e.preventDefault()
    setError(null)

    const trimmedEmail = email.trim()
    if (!trimmedEmail || !password || !confirmPassword) {
      setError('Please fill in all fields.')
      return
    }

    if (password !== confirmPassword) {
      setError('Passwords do not match.')
      return
    }

    if (password.length < 6) {
      setError('Password must be at least 6 characters.')
      return
    }

    setIsLoading(true)

    const { error: authError } = await supabase.auth.signUp({
      email: trimmedEmail,
      password,
    })

    if (authError) {
      setError(authError.message)
      setIsLoading(false)
      return
    }

    setSuccess(true)
    setIsLoading(false)
  }

  const isLogin = mode === 'login'

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent className="sm:max-w-sm">
        <DialogHeader>
          <DialogTitle>{isLogin ? 'Sign In' : 'Sign Up'}</DialogTitle>
          <DialogDescription>
            {isLogin
              ? 'Enter your credentials to access the dashboard'
              : 'Create an account to get started'}
          </DialogDescription>
        </DialogHeader>

        {success ? (
          <div className="space-y-4 text-center">
            <p className="text-sm text-muted-foreground">
              Check your email for a confirmation link to complete your
              registration.
            </p>
            <Button
              variant="outline"
              className="w-full"
              onClick={() => switchMode('login')}
            >
              Back to Sign In
            </Button>
          </div>
        ) : (
          <>
            <form
              onSubmit={isLogin ? handleLogin : handleRegister}
              className="space-y-4"
              noValidate
            >
              <div className="space-y-2">
                <Label htmlFor="auth-email">Email</Label>
                <Input
                  id="auth-email"
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  placeholder="you@example.com"
                  required
                  autoComplete="email"
                />
              </div>

              <div className="space-y-2">
                <Label htmlFor="auth-password">Password</Label>
                <Input
                  id="auth-password"
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  placeholder={
                    isLogin ? 'Your password' : 'At least 6 characters'
                  }
                  required
                  autoComplete={isLogin ? 'current-password' : 'new-password'}
                />
              </div>

              {!isLogin && (
                <div className="space-y-2">
                  <Label htmlFor="auth-confirm-password">
                    Confirm Password
                  </Label>
                  <Input
                    id="auth-confirm-password"
                    type="password"
                    value={confirmPassword}
                    onChange={(e) => setConfirmPassword(e.target.value)}
                    placeholder="Repeat your password"
                    required
                    autoComplete="new-password"
                  />
                </div>
              )}

              {error && (
                <p className="text-sm text-destructive" role="alert">
                  {error}
                </p>
              )}

              <Button type="submit" className="w-full" disabled={isLoading}>
                {isLoading
                  ? isLogin
                    ? 'Signing in...'
                    : 'Creating account...'
                  : isLogin
                    ? 'Sign In'
                    : 'Sign Up'}
              </Button>
            </form>

            <p className="text-center text-sm text-muted-foreground">
              {isLogin ? (
                <>
                  Don&apos;t have an account?{' '}
                  <button
                    type="button"
                    className="font-medium text-primary underline-offset-4 hover:underline"
                    onClick={() => switchMode('register')}
                  >
                    Sign Up
                  </button>
                </>
              ) : (
                <>
                  Already have an account?{' '}
                  <button
                    type="button"
                    className="font-medium text-primary underline-offset-4 hover:underline"
                    onClick={() => switchMode('login')}
                  >
                    Sign In
                  </button>
                </>
              )}
            </p>
          </>
        )}
      </DialogContent>
    </Dialog>
  )
}
