// react/src/components/theme/theme-toggle.tsx
'use client'

import { Moon, Sun } from 'lucide-react'
import { useTheme } from 'next-themes'
import { useEffect, useState } from 'react'

import { Button } from '@/components/ui/button'

export function ThemeToggle() {
  const { theme, setTheme } = useTheme()
  const [mounted, setMounted] = useState(false)

  useEffect(() => {
    setMounted(true)
  }, [])

  return (
    <Button
      variant="ghost"
      size="icon"
      aria-label={
        mounted
          ? `Switch to ${theme === 'dark' ? 'light' : 'dark'} mode`
          : 'Toggle theme'
      }
      onClick={() => mounted && setTheme(theme === 'dark' ? 'light' : 'dark')}
      disabled={!mounted}
    >
      <Sun className="h-5 w-5 rotate-0 scale-100 transition-transform dark:-rotate-90 dark:scale-0" />
      <Moon className="absolute h-5 w-5 rotate-90 scale-0 transition-transform dark:rotate-0 dark:scale-100" />
    </Button>
  )
}

// svelte/src/lib/components/layout/ThemeToggle.svelte
<script lang="ts">
	import { Sun, Moon } from 'lucide-svelte'
	import { theme } from '$lib/stores/theme.svelte'
</script>

<button
	type="button"
	onclick={() => theme.toggle()}
	class="relative inline-flex h-9 w-9 items-center justify-center rounded-md transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none"
	aria-label={theme.current === 'light' ? 'Switch to dark mode' : 'Switch to light mode'}
>
	<Sun
		class="h-5 w-5 rotate-0 scale-100 transition-transform dark:-rotate-90 dark:scale-0"
	/>
	<Moon
		class="absolute h-5 w-5 rotate-90 scale-0 transition-transform dark:rotate-0 dark:scale-100"
	/>
</button>
