// svelte/src/lib/components/articles/ArticleListSkeleton.svelte
<script lang="ts">
	interface Props {
		count?: number
	}

	let { count = 5 }: Props = $props()
</script>

<div role="status" aria-label="Loading articles" class="space-y-3">
	<!-- eslint-disable-next-line @typescript-eslint/no-unused-vars -->
	{#each Array(count) as _, i (i)}
		<div class="flex items-center justify-between gap-4 rounded-lg border p-4">
			<div class="min-w-0 flex-1 space-y-2">
				<div class="h-5 w-3/4 animate-pulse rounded-md bg-accent"></div>
				<div class="flex flex-wrap gap-x-4 gap-y-1">
					<div class="h-4 w-20 animate-pulse rounded-md bg-accent"></div>
					<div class="h-4 w-24 animate-pulse rounded-md bg-accent"></div>
					<div class="h-4 w-32 animate-pulse rounded-md bg-accent"></div>
				</div>
			</div>
			<div class="flex shrink-0 gap-1">
				<div class="h-8 w-8 animate-pulse rounded-md bg-accent"></div>
				<div class="h-8 w-8 animate-pulse rounded-md bg-accent"></div>
			</div>
		</div>
	{/each}
	<span class="sr-only">Loading articles, please wait...</span>
</div>

// react/src/components/articles/article-list-skeleton.tsx
import { Skeleton } from '@/components/ui/skeleton'

export function ArticleListSkeleton({ count = 5 }: { count?: number }) {
  return (
    <div role="status" aria-label="Loading articles" className="space-y-3">
      {Array.from({ length: count }).map((_, i) => (
        <div
          key={i}
          className="flex items-center justify-between gap-4 rounded-lg border p-4"
        >
          <div className="min-w-0 flex-1 space-y-2">
            <Skeleton className="h-5 w-3/4" />
            <div className="flex flex-wrap gap-x-4 gap-y-1">
              <Skeleton className="h-4 w-20" />
              <Skeleton className="h-4 w-24" />
              <Skeleton className="h-4 w-32" />
            </div>
          </div>
          <div className="flex shrink-0 gap-1">
            <Skeleton className="h-8 w-8 rounded-md" />
            <Skeleton className="h-8 w-8 rounded-md" />
          </div>
        </div>
      ))}
      <span className="sr-only">Loading articles, please wait...</span>
    </div>
  )
}
